version: '4.21.1'
services:
  app:  
    build: .
    volumes:
      - .:/paraphraser
    image: app
    container_name: paraphraser_container
    command: uvicorn test:app --host 0.0.0.0 --port 8000

  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
